"use client";
import { useMemo, useState } from "react";
import { appliances, applianceKeys, type ApplianceKey } from "@/lib/appliances";
import { calculateLife } from "@/lib/life";
import NumberInput from "@/components/NumberInput";

export default function ApplianceLifeCalculator() {
  const [item, setItem] = useState<ApplianceKey>("washer");
  const [age, setAge] = useState(7); const [condition, setCondition] = useState(3); const [maintenance, setMaintenance] = useState(3); const [usage, setUsage] = useState(3);
  const result = useMemo(() => calculateLife({ age, benchmark: appliances[item].typicalLife, condition, maintenance, usage }), [age, condition, item, maintenance, usage]);
  return <section className="calculator-card" aria-labelledby="life-calculator-title"><div className="calculator-heading"><p className="eyebrow">Appliance life estimator</p><h2 id="life-calculator-title">How much replacement pressure is building?</h2><p>Use age, condition, maintenance, and usage to create a transparent planning estimate. It is not a failure prediction.</p></div><div className="calculator-grid"><label>Appliance<select value={item} onChange={(e) => { const next = e.target.value as ApplianceKey; setItem(next); setAge(Math.round(appliances[next].typicalLife * .65)); }}>{applianceKeys.map((key) => <option key={key} value={key}>{appliances[key].label}</option>)}</select></label><label>Age (years)<NumberInput min={0} max={60} value={age} onChange={setAge} /></label><label>Overall condition<select value={condition} onChange={(e) => setCondition(Number(e.target.value))}><option value="1">Poor</option><option value="2">Fair</option><option value="3">Average</option><option value="4">Good</option><option value="5">Excellent</option></select></label><label>Maintenance history<select value={maintenance} onChange={(e) => setMaintenance(Number(e.target.value))}><option value="1">Rarely maintained</option><option value="2">Inconsistent</option><option value="3">Average</option><option value="4">Usually maintained</option><option value="5">Well maintained</option></select></label><label>Usage intensity<select value={usage} onChange={(e) => setUsage(Number(e.target.value))}><option value="1">Light</option><option value="2">Below average</option><option value="3">Average</option><option value="4">Heavy</option><option value="5">Very heavy</option></select></label></div>{result ? <><div className="result" aria-live="polite"><div><span className="result-label">Planning result</span><strong>{result.label}</strong></div><div><span className="result-label">Replacement pressure</span><strong>{result.score}/100</strong></div></div><div className="result-notes"><p><strong>Benchmark time remaining:</strong> {result.yearsRemaining > 0 ? `about ${result.yearsRemaining} years` : "at or beyond the benchmark"}. This is not a warranty or failure date.</p></div><div className="reason-list"><strong>What moved the result</strong><ul>{result.notes.map((note) => <li key={note}>{note}</li>)}</ul></div></> : <p className="input-error" role="status">Check the highlighted fields to see the estimate.</p>}<details><summary>How this estimate works</summary><p>Age contributes up to 55 points, condition up to 20, maintenance up to 15, and usage up to 10. The score is rounded and capped at 100. It is a planning aid that should be combined with diagnosis, repair cost, replacement cost, safety, and local installation requirements.</p></details></section>;
}
