export type Guide = {
  slug: string;
  title: string;
  description: string;
  appliance: string;
  calculator: string;
  intro: string;
  signs: string[];
  steps: string[];
  takeaway: string;
  context: string;
  questions: string[];
};

export const guides: Guide[] = [
  { slug: "is-it-worth-repairing-a-10-year-old-washer", title: "Is It Worth Repairing a 10-Year-Old Washer?", description: "A practical way to compare a 10-year-old washer repair quote with replacement cost, condition, and remaining useful life.", appliance: "washer", calculator: "/repair-or-replace/washer", intro: "A 10-year-old washer is near the service-life benchmark used by many planning guides, but age alone does not decide the question. The repair cost, failure type, condition, and replacement quote matter more than a single cutoff.", signs: ["A modest repair on a quiet, leak-free machine can still be sensible.", "Bearing noise, tub leaks, corrosion, repeated failures, or a control board plus another major part increase replacement pressure.", "Compare installed replacement cost, delivery, haul-away, and tax with the complete repair quote."], steps: ["Write down the complete repair quote, including diagnostic, labor, parts, and any return visit.", "Get a realistic replacement number for an equivalent capacity and installation.", "Run those numbers through the washer calculator, then treat the result as a first-pass screen rather than a diagnosis."], takeaway: "At 10 years, repair is most defensible when the failure is isolated and the total quote is comfortably below replacement. A major leak or repeated failure can justify replacement even when the math looks close.", context: "Do not treat the 10-year mark as an expiration date. A lightly used, maintained washer with one well-defined failure can have a very different outlook from a heavily used machine with bearing noise, corrosion, leaks, and prior repairs.", questions: ["Is the quoted repair for one confirmed failure, or are there signs of another major problem?", "Does the replacement quote include delivery, installation, required hoses, haul-away, and tax?", "Would you still choose this washer today if the repair restored normal operation?"] },
  { slug: "how-much-should-i-spend-repairing-a-refrigerator", title: "How Much Should I Spend Repairing a Refrigerator?", description: "Use repair cost, replacement cost, age, and failure type to set a refrigerator repair budget.", appliance: "refrigerator", calculator: "/repair-or-replace/refrigerator", intro: "There is no universal refrigerator repair limit. A $400 repair can be reasonable on a newer refrigerator and a poor bet on an older unit with a sealed-system problem. Start with the complete replacement alternative, then compare the repair ratio.", signs: ["Door seals, fans, sensors, and some ice-maker issues can be contained repairs.", "Compressor, sealed-system, cooling, or multiple-control failures deserve a careful replacement comparison.", "Include food risk, temporary storage, delivery, installation, and haul-away in the practical decision."], steps: ["Ask the technician which part failed and whether the diagnosis is certain.", "Price an equivalent replacement, including delivery and installation.", "Enter both figures and the refrigerator age in the calculator, then read the factors that move the score."], takeaway: "A repair quote should be judged against the replacement total and the refrigerator's failure history, not against a percentage rule used without context.", context: "Refrigerators deserve extra attention because the same dollar quote can represent very different failures. A contained fan or sensor repair is not economically equivalent to a major cooling-system problem. Repeat visits and lost food can also make a marginal repair less attractive.", questions: ["What component failed, and how confident is the technician in the diagnosis?", "Is any major cooling-system or sealed-system work included in the quote?", "Does the replacement comparison include delivery, installation, haul-away, and fit changes?"] },
  { slug: "when-should-i-replace-a-water-heater", title: "When Should I Replace a Water Heater?", description: "Learn which water-heater symptoms make replacement more urgent than another repair call.", appliance: "water-heater", calculator: "/repair-or-replace/water-heater", intro: "Water heaters combine cost, age, leaks, corrosion, and safety considerations. A replaceable thermostat or element may be worth repairing, while a leaking tank usually changes the decision completely.", signs: ["A tank leak, active corrosion, or water around the tank is a replacement and safety question, not just a repair-price question.", "An isolated element, thermostat, valve, or igniter issue can be repairable on a sound unit.", "Fuel type, venting, code requirements, expansion tanks, and installation labor affect the replacement quote."], steps: ["Identify whether the tank itself is leaking or a replaceable connection or component is involved.", "Ask for a written repair scope and an installed replacement estimate.", "Use the calculator to organize the financial comparison, then follow local code and professional safety guidance."], takeaway: "When the tank is leaking or badly corroded, replacement normally deserves priority. When the tank is sound, compare the repair scope with an installed replacement rather than guessing from age alone.", context: "A water-heater decision is not purely financial when water, fuel, venting, combustion, or electrical hazards are involved. The source of a leak matters: water from a serviceable fitting is different from a failed tank. Code-related installation work can also materially change replacement cost.", questions: ["Is the tank itself leaking, or is water coming from a replaceable valve, pipe, or fitting?", "Does the replacement quote include code-required installation work and disposal?", "Are there corrosion, venting, combustion, electrical, or other safety concerns?"] },
  { slug: "should-i-repair-or-replace-a-dryer", title: "Should I Repair or Replace a Dryer?", description: "A transparent dryer repair decision using age, repair cost, replacement cost, and condition.", appliance: "dryer", calculator: "/repair-or-replace/dryer", intro: "Dryers often have repairable belts, rollers, switches, and heating components, but repeated overheating or motor and control problems can change the economics. Use the complete quote and the machine's condition.", signs: ["A contained part failure on an otherwise quiet dryer is often a repair-friendly scenario.", "Repeated overheating, a failing motor, damaged drum, or multiple recent repairs increase replacement pressure.", "Check venting and airflow because a restricted vent can create performance and safety problems that a part replacement will not solve."], steps: ["Separate the appliance repair from any venting or installation work that also needs attention.", "Compare the quote with an equivalent installed dryer, including haul-away.", "Use the dryer guide and calculator to record the assumptions behind the decision."], takeaway: "Dryer repair is often reasonable when the failure is isolated and the unit is otherwise sound. Repeated heat or motor problems call for a broader replacement comparison.", context: "A dryer's symptoms can come from the appliance, the vent system, or both. Slow drying and overheating should not automatically be treated as a failed heating component. Restricted venting can reduce performance and create a safety concern.", questions: ["Has the vent path and exterior termination been checked for safe airflow?", "Is the repair an isolated wear item or a motor, drum, control, or repeated heat problem?", "Does the replacement number include installation pieces and haul-away?"] },
  { slug: "is-a-dishwasher-repair-worth-it", title: "Is a Dishwasher Repair Worth It?", description: "Decide whether a dishwasher repair makes sense using age, leak risk, condition, and replacement cost.", appliance: "dishwasher", calculator: "/repair-or-replace/dishwasher", intro: "Dishwasher decisions are shaped by the repair type and by leak risk. A latch, hose, sensor, or pump repair can be contained; rust, recurring leaks, and multiple control failures deserve more caution.", signs: ["A modest repair on a newer, dry, reliable dishwasher can be a sensible choice.", "Tub corrosion, recurring leaks, damaged racks, or several recent repairs point toward replacement.", "Include cabinet fit, installation labor, shutoff access, and haul-away in a replacement estimate."], steps: ["Confirm whether the leak is from a replaceable hose or valve versus the tub or structure.", "Get a complete repair price and compare it with an installed equivalent.", "Run the inputs through the dishwasher calculator and record what remains uncertain."], takeaway: "The most useful dishwasher question is whether the current failure is isolated. A low quote does not make a corroded or repeatedly leaking unit a good long-term bet.", context: "Water-damage risk makes the location and cause of a dishwasher leak important. A replaceable hose, seal, or valve is different from deterioration of the tub or structure. Determine whether the repair addresses the actual source and whether surrounding materials were affected.", questions: ["Is the leak source positively identified and part of a replaceable component?", "Are there signs of tub corrosion, damaged racks, or deterioration beyond the quoted failure?", "Does replacement require plumbing, electrical, cabinet-fit, or flooring work beyond the appliance price?"] },
  { slug: "is-hvac-repair-worth-the-cost", title: "Is HVAC Repair Worth the Cost?", description: "A first-pass way to compare HVAC repair cost with replacement while keeping diagnosis and safety first.", appliance: "hvac", calculator: "/repair-or-replace/hvac", intro: "HVAC economics are more complex than a simple age rule. Diagnosis, safety, refrigerant, efficiency, compatibility, and installation details can outweigh a calculator score, so use the numbers to structure a conversation with a qualified professional.", signs: ["An isolated repair on a younger, well-maintained system can be reasonable.", "Repeated breakdowns, a compressor or heat-exchanger issue, refrigerant concerns, or major efficiency differences deserve a replacement comparison.", "A replacement quote should explain equipment, labor, permits, disposal, and what happens to ductwork, line sets, or electrical service."], steps: ["Get a written diagnosis and ask what evidence supports it.", "Request an installed replacement estimate with equivalent capacity and efficiency assumptions.", "Use the HVAC calculator as a financial screen, never as a substitute for safety or diagnosis."], takeaway: "HVAC repair is worth considering when the diagnosis is clear and the system is otherwise sound. For major components or repeated failures, compare complete installed alternatives and professional recommendations.", context: "HVAC replacement comparisons need like-for-like scope. Equipment price alone is not an installed-system quote, and efficiency changes can involve controls, electrical work, venting, refrigerant work, or other requirements. Comfort problems can also originate in ductwork or the building envelope.", questions: ["What exact failure was diagnosed, and what testing supports it?", "Are the repair and replacement quotes comparing the same scope and solving the same problem?", "Do safety, refrigerant, combustion, electrical, or compatibility issues limit repair regardless of price?"] },
];

export const guideSlugs = guides.map((guide) => guide.slug);
export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
